---
- name: Fail if vault_newrelic_license is not defined
  fail:
    msg: vault_newrelic_license is not defined
  when: vault_newrelic_license is not defined

- include_tasks: install.yml
- include_tasks: ini.yml
